# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Expenses

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/expenses:latest
  
  deploy:
    runs-on: ubuntu-latest   
    needs: [docker]
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        # TODO: add env vars as secrets on GitHub
        with:
          # VPS IP
          host: ${{ secrets.VPS_SSH_HOST }}
          # VPS username
          username: ${{ secrets.VPS_SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # SSH port
          port: ${{ secrets.VPS_SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Recreate folder"
            rm -rf /var/www/expenses/prd
            mkdir /var/www/expenses/prd
            cd /var/www/expenses/prd
            wget https://raw.githubusercontent.com/renatojsilvas/expenses/main/docker-compose.yml
            wget https://raw.githubusercontent.com/renatojsilvas/expenses/main/nginx.conf
            echo "Pull new image"
            docker-compose -f /var/www/expenses/prd/docker-compose.yml pull
            echo "Restart the container"
            docker-compose -f /var/www/expenses/prd/docker-compose.yml up --force-recreate --build --no-deps -d
            echo "Delete old image"
            docker image prune -f